apiVersion: apps/v1
kind: Deployment
metadata:
  namespace : katana-team-0-ns
  name: chall-notekeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chall-notekeeper
  template:
    metadata:
      labels:
        app: chall-notekeeper
    spec:
      containers:
        - name: chall-notekeeper-team-0
          image: notekeeper:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: katana-team-0-ns
  name: chall-notekeeper-service
spec:
  type: NodePort
  selector:
    app: chall-notekeeper
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
