apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: create-deploy
rules:
  - apiGroups: ["apps"]
    #
    # at the HTTP level, the name of the resource for accessing Deployment
    # objects is "deployments"
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
